// AUTO-GENERATED by scripts/generate-muse-model-catalog.mjs — do not edit by hand.
// Snapshot of src/config/videoModelSpecs.ts for the Deno edge runtime.
// Regenerate with: bun scripts/generate-muse-model-catalog.mjs

export interface MuseModeSpec {
  durations: number[];
  resolutions: { label: string; pricingId: string | null }[];
  aspectRatios: string[];
  audio: boolean;
  inputs: Record<string, unknown>;
}

export interface MuseModelSpec {
  id: string;
  displayName: string;
  family: string;
  provider: string;
  edgeFunction: string;
  uiGroup: string;
  modes: Record<string, MuseModeSpec>;
}

export const MUSE_VIDEO_MODELS: MuseModelSpec[] = [
  {
    "id": "seedance-2-5",
    "displayName": "Seedance 2.5",
    "family": "seedance",
    "provider": "ByteDance",
    "edgeFunction": "generate-seedance25-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          },
          {
            "label": "480p",
            "pricingId": "seedance-2-5-480p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          },
          {
            "label": "480p",
            "pricingId": "seedance-2-5-480p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "firstLast": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          },
          {
            "label": "480p",
            "pricingId": "seedance-2-5-480p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      },
      "reference": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          },
          {
            "label": "480p",
            "pricingId": "seedance-2-5-480p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": true,
        "inputs": {
          "images": {
            "min": 1,
            "max": 30
          },
          "videos": {
            "min": 0,
            "max": 10
          },
          "audios": {
            "min": 0,
            "max": 10
          }
        }
      },
      "v2v": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": true,
        "inputs": {
          "videos": {
            "min": 1,
            "max": 10
          }
        }
      },
      "edit": {
        "durations": [
          4,
          5,
          8,
          10,
          12,
          15,
          20,
          25,
          30
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-2-5"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "videos": {
            "min": 1,
            "max": 1
          }
        }
      }
    }
  },
  {
    "id": "seedance-standard",
    "displayName": "Seedance 2.0 Fast",
    "family": "seedance",
    "provider": "ByteDance",
    "edgeFunction": "generate-seedance-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          3,
          5,
          8,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          5,
          8,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "seedance-pro",
    "displayName": "Seedance 2.0",
    "family": "seedance",
    "provider": "ByteDance",
    "edgeFunction": "generate-seedance-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          3,
          5,
          8,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-pro"
          },
          {
            "label": "1080p",
            "pricingId": "seedance-pro-1080p"
          },
          {
            "label": "4K",
            "pricingId": "seedance-pro-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          5,
          8,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-pro"
          },
          {
            "label": "1080p",
            "pricingId": "seedance-pro-1080p"
          },
          {
            "label": "4K",
            "pricingId": "seedance-pro-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "seedance-mini",
    "displayName": "Seedance 1 Lite",
    "family": "seedance",
    "provider": "ByteDance",
    "edgeFunction": "generate-seedance-video",
    "uiGroup": "economy",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-mini"
          },
          {
            "label": "480p",
            "pricingId": "seedance-mini"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-mini"
          },
          {
            "label": "480p",
            "pricingId": "seedance-mini"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      },
      "firstLast": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "seedance-mini"
          },
          {
            "label": "480p",
            "pricingId": "seedance-mini"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9",
          "9:21"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      }
    }
  },
  {
    "id": "kling-2.5-turbo",
    "displayName": "Kling 2.5 Turbo",
    "family": "kling",
    "provider": "Kuaishou",
    "edgeFunction": "generate-kling-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-2.5-turbo"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-2.5-turbo"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "kling-2.6",
    "displayName": "Kling 2.6",
    "family": "kling",
    "provider": "Kuaishou",
    "edgeFunction": "generate-kling-video",
    "uiGroup": "audio",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-2.6"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-2.6"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "kling-3",
    "displayName": "Kling 3.0",
    "family": "kling",
    "provider": "Kuaishou",
    "edgeFunction": "generate-kling-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-3"
          },
          {
            "label": "4K",
            "pricingId": "kling-3-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-3"
          },
          {
            "label": "4K",
            "pricingId": "kling-3-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "kling-omni",
    "displayName": "Kling 3.0 Omni",
    "family": "kling",
    "provider": "Kuaishou",
    "edgeFunction": "generate-kling-video",
    "uiGroup": "professional",
    "modes": {
      "t2v": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-omni"
          },
          {
            "label": "4K",
            "pricingId": "kling-omni-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-omni"
          },
          {
            "label": "4K",
            "pricingId": "kling-omni-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "reference": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-omni"
          },
          {
            "label": "4K",
            "pricingId": "kling-omni-4k"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": true,
        "inputs": {
          "images": {
            "min": 1,
            "max": 7
          }
        }
      },
      "v2v": {
        "durations": [
          3,
          5,
          8,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "kling-omni"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1"
        ],
        "audio": false,
        "inputs": {
          "videos": {
            "min": 1,
            "max": 1
          },
          "images": {
            "min": 0,
            "max": 4
          }
        }
      }
    }
  },
  {
    "id": "veo-3.1-lite-720p",
    "displayName": "Veo 3.1 Lite",
    "family": "veo",
    "provider": "Google",
    "edgeFunction": "generate-veo-video",
    "uiGroup": "audio",
    "modes": {
      "t2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "veo-3.1-lite-720p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "veo-3.1-lite-720p"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "reference": {
        "durations": [
          8
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "veo-3.1-lite-720p"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": true,
        "inputs": {
          "images": {
            "min": 1,
            "max": 3
          }
        }
      }
    }
  },
  {
    "id": "veo-3.1-fast",
    "displayName": "Veo 3.1 Fast",
    "family": "veo",
    "provider": "Google",
    "edgeFunction": "generate-veo-video",
    "uiGroup": "audio",
    "modes": {
      "t2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-fast"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-fast"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "reference": {
        "durations": [
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-fast"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": true,
        "inputs": {
          "images": {
            "min": 1,
            "max": 3
          }
        }
      }
    }
  },
  {
    "id": "veo-3.1-pro",
    "displayName": "Veo 3.1 Pro",
    "family": "veo",
    "provider": "Google",
    "edgeFunction": "generate-veo-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          4,
          6,
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "reference": {
        "durations": [
          8
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "veo-3.1-pro"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": true,
        "inputs": {
          "images": {
            "min": 1,
            "max": 3
          }
        }
      }
    }
  },
  {
    "id": "grok-imagine",
    "displayName": "Grok Imagine",
    "family": "grok",
    "provider": "xAI",
    "edgeFunction": "generate-grok-video",
    "uiGroup": "audio",
    "modes": {
      "t2v": {
        "durations": [
          5,
          6,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "grok-imagine"
          },
          {
            "label": "480p",
            "pricingId": "grok-imagine"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "3:2",
          "2:3"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          6,
          10,
          12,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "grok-imagine"
          },
          {
            "label": "480p",
            "pricingId": "grok-imagine"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "3:2",
          "2:3"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "ltx-standard",
    "displayName": "LTX 2.3 Fast",
    "family": "ltx",
    "provider": "Lightricks",
    "edgeFunction": "generate-ltx-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          20
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "ltx-standard"
          },
          {
            "label": "2K",
            "pricingId": "ltx-standard"
          },
          {
            "label": "4K",
            "pricingId": "ltx-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          20
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "ltx-standard"
          },
          {
            "label": "2K",
            "pricingId": "ltx-standard"
          },
          {
            "label": "4K",
            "pricingId": "ltx-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      }
    }
  },
  {
    "id": "ltx-pro",
    "displayName": "LTX 2.3 Pro",
    "family": "ltx",
    "provider": "Lightricks",
    "edgeFunction": "generate-ltx-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          6,
          8,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "ltx-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          6,
          8,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "ltx-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "wan-2-7-standard",
    "displayName": "Wan 2.7",
    "family": "wan",
    "provider": "Alibaba Wan",
    "edgeFunction": "generate-wan-video",
    "uiGroup": "audio",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "wan-2-7-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "wan-2-7-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "wan-2-7-pro",
    "displayName": "Wan 2.7 Pro",
    "family": "wan",
    "provider": "Alibaba Wan",
    "edgeFunction": "generate-wan-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "wan-2-7-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "wan-2-7-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "wan-2-6-standard",
    "displayName": "Wan 2.6",
    "family": "wan",
    "provider": "Wan Video",
    "edgeFunction": "generate-wan-video",
    "uiGroup": "economy",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "wan-2-6-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "wan-2-6-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "wan-2-6-pro",
    "displayName": "Wan 2.6 Pro",
    "family": "wan",
    "provider": "Wan Video",
    "edgeFunction": "generate-wan-video",
    "uiGroup": "economy",
    "modes": {
      "t2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "wan-2-6-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5,
          10,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "wan-2-6-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "hailuo-standard",
    "displayName": "Hailuo 2.3",
    "family": "hailuo",
    "provider": "MiniMax",
    "edgeFunction": "generate-hailuo-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          6,
          10
        ],
        "resolutions": [
          {
            "label": "768p",
            "pricingId": "hailuo-standard"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          6,
          10
        ],
        "resolutions": [
          {
            "label": "768p",
            "pricingId": "hailuo-standard"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "hailuo-pro",
    "displayName": "Hailuo 2.3 Pro",
    "family": "hailuo",
    "provider": "MiniMax",
    "edgeFunction": "generate-hailuo-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          6,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "hailuo-pro"
          },
          {
            "label": "768p",
            "pricingId": "hailuo-pro"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          6,
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "hailuo-pro"
          },
          {
            "label": "768p",
            "pricingId": "hailuo-pro"
          }
        ],
        "aspectRatios": [
          "16:9"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "luma-ray32-5s",
    "displayName": "Luma Ray 3.2 (5s)",
    "family": "luma",
    "provider": "Luma AI",
    "edgeFunction": "generate-luma-video",
    "uiGroup": "professional",
    "modes": {
      "t2v": {
        "durations": [
          5
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "720p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "540p",
            "pricingId": "luma-ray32-5s"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          5
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "720p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "540p",
            "pricingId": "luma-ray32-5s"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      },
      "firstLast": {
        "durations": [
          5
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "720p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "540p",
            "pricingId": "luma-ray32-5s"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      },
      "lastFrame": {
        "durations": [
          5
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "720p",
            "pricingId": "luma-ray32-5s"
          },
          {
            "label": "540p",
            "pricingId": "luma-ray32-5s"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": false,
        "inputs": {
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": false
        }
      }
    }
  },
  {
    "id": "luma-ray32-10s",
    "displayName": "Luma Ray 3.2 (10s)",
    "family": "luma",
    "provider": "Luma AI",
    "edgeFunction": "generate-luma-video",
    "uiGroup": "professional",
    "modes": {
      "t2v": {
        "durations": [
          10
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "luma-ray32-10s"
          },
          {
            "label": "720p",
            "pricingId": "luma-ray32-10s"
          },
          {
            "label": "540p",
            "pricingId": "luma-ray32-10s"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4",
          "21:9"
        ],
        "audio": false,
        "inputs": {}
      }
    }
  },
  {
    "id": "vidu-q2-reference",
    "displayName": "Vidu Q3 Pro",
    "family": "vidu",
    "provider": "Shengshu AI",
    "edgeFunction": "generate-vidu-video",
    "uiGroup": "professional",
    "modes": {
      "t2v": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-reference"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-reference"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "firstLast": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-reference"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-reference"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      }
    }
  },
  {
    "id": "vidu-q2-i2v",
    "displayName": "Vidu Q3 Pro I2V",
    "family": "vidu",
    "provider": "Shengshu AI",
    "edgeFunction": "generate-vidu-video",
    "uiGroup": "fast",
    "modes": {
      "i2v": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-i2v"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-i2v"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-i2v"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true
        }
      },
      "firstLast": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-i2v"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-i2v"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-i2v"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {
          "firstFrame": true,
          "lastFrame": true,
          "lastFrameRequiresFirstFrame": true
        }
      }
    }
  },
  {
    "id": "vidu-q2-t2v",
    "displayName": "Vidu Q3 Turbo",
    "family": "vidu",
    "provider": "Shengshu AI",
    "edgeFunction": "generate-vidu-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          4,
          5,
          6,
          8,
          10,
          12,
          16
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "vidu-q2-t2v"
          },
          {
            "label": "720p",
            "pricingId": "vidu-q2-t2v"
          },
          {
            "label": "540p",
            "pricingId": "vidu-q2-t2v"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": true,
        "inputs": {}
      }
    }
  },
  {
    "id": "happyhorse-standard",
    "displayName": "HappyHorse 1.0",
    "family": "happyhorse",
    "provider": "Alibaba",
    "edgeFunction": "generate-happyhorse-video",
    "uiGroup": "fast",
    "modes": {
      "t2v": {
        "durations": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "happyhorse-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "resolutions": [
          {
            "label": "720p",
            "pricingId": "happyhorse-standard"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  },
  {
    "id": "happyhorse-pro",
    "displayName": "HappyHorse 1.0 Pro",
    "family": "happyhorse",
    "provider": "Alibaba",
    "edgeFunction": "generate-happyhorse-video",
    "uiGroup": "flagship",
    "modes": {
      "t2v": {
        "durations": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "happyhorse-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": false,
        "inputs": {}
      },
      "i2v": {
        "durations": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        "resolutions": [
          {
            "label": "1080p",
            "pricingId": "happyhorse-pro"
          }
        ],
        "aspectRatios": [
          "16:9",
          "9:16",
          "1:1",
          "4:3",
          "3:4"
        ],
        "audio": false,
        "inputs": {
          "firstFrame": true
        }
      }
    }
  }
];

export function getMuseModel(id: string): MuseModelSpec | undefined {
  return MUSE_VIDEO_MODELS.find((m) => m.id === id);
}
